### ISSUE TITLE
遇到什么问题了？为什么没有继续开发了？

### ISSUE THREAD

**Issue by kphcdr** [qiqizjl/hyperf-ide-helper#1]

**Comment by qiqizjl** [comment]
没有遇到问题哦 因为该有的功能都有了 所以暂时木有更新哦。如果有需要新功能可以在issue里提出来哦

**Comment by qiqizjl** [comment]
没有遇到问题哦、、最近有点忙 已经在整理最新的版本。准备在五一完成1.0的release

**Comment by qiqizjl** [comment]
已经完成model生成 发布1.0.0版本
