### ISSUE TITLE
可以升级 dbal 到 ^3.0 吗？

### ISSUE THREAD

**Issue by huangdijia** [qiqizjl/hyperf-ide-helper#2]
由于 hyperf/database 开始使用 dbal 3.x ，与当前项目使用的 2.x 有一个接口冲突了，导致不能正常使用。

**Comment by huangdijia** [comment]
我已经 fork 了，看源码发现根本没用到 dbal

**Comment by qiqizjl** [comment]
v1.2.1已升级

https://github.com/qiqizjl/hyperf-ide-helper/blob/master/src/Command/Model.php#L304

是Laravel/Hyperf底层调用了dbal
